# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 11:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='shipper_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=4326),
        ),
    ]
