# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 11:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porter',
            name='average_quote',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='porter',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='porter',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
