# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porters', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='porters',
            field=models.ManyToManyField(blank=True, null=True, to='porters.Porter'),
        ),
    ]
